# Generated by Django 6.1 on 2026-08-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yatri',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
