# Generated by Django 6.1 on 2026-08-27 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'single contact', 'verbose_name_plural': 'more contct'},
        ),
        migrations.AlterModelTable(
            name='contact',
            table='Student information',
        ),
    ]
